name: Android Static Build nftables

on:
  workflow_dispatch:
    inputs:
      target_arch:
        description: 'Target architecture (aarch64/arm/x86_64/i686)'
        required: false
        default: 'aarch64'
      ndk_version:
        description: 'Android NDK version'
        required: false
        default: 'r27c'
      android_api:
        description: 'Android API level'
        required: false
        default: '30'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ github.event.inputs.ndk_version || 'r27c' }}

      - name: Verify NDK installation
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          ls -l $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin || echo "NDK toolchain directory not found"
          find $ANDROID_NDK_HOME -name '*clang' | grep -E 'aarch64-linux-android|armv7a-linux-androideabi|x86_64-linux-android|i686-linux-android' || echo "No clang compilers found"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/sysroot
            ${{ github.workspace }}/gmp-6.3.0
            ${{ github.workspace }}/libmnl
            ${{ github.workspace }}/libnftnl
          key: ${{ runner.os }}-ndk-${{ github.event.inputs.ndk_version || 'r27c' }}-${{ github.event.inputs.target_arch || 'aarch64' }}-${{ github.event.inputs.android_api || '30' }}-${{ hashFiles('**/configure.ac', '**/Makefile.am') }}

      - name: Install build tools
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y git asciidoc automake autoconf libtool libltdl-dev pkg-config gcc perl flex bison libgmp-dev libreadline-dev build-essential

      - name: Prepare source code
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          git clone https://git.netfilter.org/libmnl
          git clone https://git.netfilter.org/libnftnl
          [ ! -f gmp-6.3.0.tar.xz ] && wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
          tar -xf gmp-6.3.0.tar.xz

      - name: Setup toolchain
        run: |
          case "${{ github.event.inputs.target_arch || 'aarch64' }}" in
            aarch64) target="aarch64-linux-android" ;;
            arm) target="armv7a-linux-androideabi" ;;
            x86_64) target="x86_64-linux-android" ;;
            i686)
